@BaseUrl = http://localhost:4000
@AccessToken = CfDJ8OPNDYaggNlNt0hO6O-TB1CbnT1lonGCNV903ch6KodpwZv6DssN7BmBP8CbLUo9Kwso8rQzzJuoTT_h_CaTreFehW842XD4eCYSSsD5Cr_frFDnVR-4IYb_rwu8N9EttwOcwldGUcv-bSfdZJ7dXQ6i-uUxfWFnGIPuFXe7il8VcYrrkk6qub72JgeKoW9oADdqimReJpvEwgl0vvYqrrYlE1b7hMJ8NJr342hZx099Ao5I8D8Cixi7x7bPkL72T1SF37OAdE-svir_vhcGBUaXuvUp3RBNkpITniKlhf_rkv7hKaLWzmJEzQ43G5yRzluFnSZlLPxNpo3pU-j0HKrKr37MKrY9S_efa0sqqvvaFKvvsmeQh-8HMRng0BQ09W89WlUOv07ORrWJo86UiX4XBLnV6fO9qV69ftD3k9QTn_yEcs3xvcTk5FAzFt4o2TQggid2-zJw51KmvxfLdmMQBSCV3gRtDfBF3egiyuWqzZ71eGf8l_PDDZNjGDc3kw

### Login
GET {{BaseUrl}}/login?firstApi=true&secondApi=true&masterApi=false

### Proxy api/hello
GET {{BaseUrl}}/first-api/hello
Authorization: Bearer {{AccessToken}}

### Proxy api/hello
GET {{BaseUrl}}/first-api/hello
Authorization: Bearer {{AccessToken}}
X-Api-Version: 1

### Proxy api/hello
GET {{BaseUrl}}/first-api/hello
Authorization: Bearer {{AccessToken}}
X-Api-Version: 2

### Proxy api/v1/hello
GET {{BaseUrl}}/first-api/v1/hello
Authorization: Bearer {{AccessToken}}

### Proxy api/v2/hello
GET {{BaseUrl}}/first-api/v2/hello
Authorization: Bearer {{AccessToken}}

### Proxy api2/hello
GET {{BaseUrl}}/second-api/v1/hello
Authorization: Bearer {{AccessToken}}

### Proxy api2/hello
GET {{BaseUrl}}/second-api/v2/hello
Authorization: Bearer {{AccessToken}}