version: '3.8'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    container_name: api
    build:
      context: .
      dockerfile: src/Yarp.Auth.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 5000:8080
      - 5001:8081
    networks:
      - proxybackend

  api2:
    image: ${DOCKER_REGISTRY-}api
    container_name: api2
    build:
      context: .
      dockerfile: src/Yarp.Auth.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 6000:8080
      - 6001:8081
    networks:
      - proxybackend

  gateway:
    image: ${DOCKER_REGISTRY-}gateway
    container_name: gateway
    build:
      context: .
      dockerfile: src/Yarp.Auth.Gateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 4000:8080
      - 4001:8081
    networks:
      - proxybackend

networks:
  proxybackend:
    name: proxybackend
    driver: bridge


